spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    username: 765553928@qq.com
    password: yilweouqqudpbfeb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080
doubanUrl:
  isbnUrl: "https://api.douban.com/v2/book/isbn/"
EmailTemplate:
  virTitle: "恭喜您成功注册"
  virBody: "<h1>验证码10分钟后失效，请在规定时间内进行验证。验证码为：</h1>"
  appointTitle: "您预约的书籍有书了！"