spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gdccwxx.com:3306/dbgirl
    username: public
    password: 502verygood
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true